name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Choose the appropriate Node.js version

      - name: Use the Secret
        env:
          API_KEY: ${{ secrets.WATHER_KEY }}
        run: |
          echo "The secret value is: $API_KEY"
          node index.js  # Run your JavaScript code with the API key as an environment variable
